site_name: ByKimber.com
site_url: https://bykimber.com

docs_dir: docs

nav:
  - Home: index.md
  - About: about-me.md
  - Services: my-services.md
  - My Projects: 
    - book-projects/index.md
    - book-projects/dragon-witch.md
    - book-projects/butterfly-house.md
    - book-projects/teeth.md
    - book-projects/the-hidden.md
  - Grammar Guide: 
    - grammar-guide/index.md
    - grammar-guide/substantive-editing.md
    - grammar-guide/copyediting.md
    - grammar-guide/phrases-of-speech.md
    - grammar-guide/common-confusions.md
    - grammar-guide/sentence-structures.md
    - grammar-guide/pov-tense-tone.md
    - grammar-guide/punctuation.md
    - grammar-guide/numbers.md
    - grammar-guide/style-guides.md
    - grammar-guide/grammar-tips.md
  - Writing Guide: 
    - writing-guide/index.md
    - writing-guide/prewriting-checklist.md
    - writing-guide/writing-process.md
    - writing-guide/world-building.md
    - writing-guide/character-development.md
    - writing-guide/theme-work.md
    - writing-guide/story-outlining.md
    - writing-guide/chapter-outlining.md
    - writing-guide/genre-guidelines.md
    - writing-guide/inclusive-language.md
    - writing-guide/manuscript-formatting.md
    - writing-guide/writing-tips.md
  - Reading List: reading-list.md

use_directory_urls: true

theme:
  name: 'material'
  logo: assets/logo.png
  features:
    - navigation.sections
    - navigation.tabs
    - navigation.tabs.sticky
    - navigation.path
    - navigation.prune
    - nvagiation.indexes
    - toc.integrate
  palette:
    # Light mode
    - media: "(prefers-color-scheme: light)"
      scheme: lightish
      toggle:
        icon: material/weather-sunny
        name: Switch to dark mode
    # Dark mode
    - media: "(prefers-color-scheme: dark)"
      scheme: darkish
      toggle:
        icon: material/weather-night
        name: Switch to light mode

plugins:
  - search
  - roamlinks:
      enable_wikilinks: true

extra:
  homepage: https://bykimber.com

markdown_extensions:
  - footnotes
  - attr_list
  - pymdownx.arithmatex:
      generic: true
  - pymdownx.superfences
  - pymdownx.details
  - pymdownx.magiclink
  - pymdownx.tasklist:
      custom_checkbox: true
  - def_list
  - pymdownx.critic
  - pymdownx.caret
  - pymdownx.keys
  - pymdownx.mark
  - pymdownx.tilde
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:pymdownx.superfences.fence_code_format
  - toc:
      permalink: true

extra_css:
  - stylesheets/extra.css